name: $(Date:yyyyMMdd)_$(Rev:rrr)

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  caminhoProjeto: 'src/SimpleAPI/SimpleAPI.csproj'

steps:

- task: CmdLine@2
  displayName: 'Executar Script'
  inputs:
    script: |
      echo string de conexao $(CONNECTION_STRING)

- task: DotNetCoreCLI@2
  displayName: 'Restore App'
  inputs:
    command: 'restore'
    projects: '$(caminhoProjeto)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build App'
  inputs:
    command: 'build'
    projects: '$(caminhoProjeto)'

- task: DotNetCoreCLI@2
  displayName: 'Publish App'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--configuration $(buildConfiguration)'   

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Artefato'
    publishLocation: 'Container'